dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install .
script: 
  - flake8 src tests
  - pytest tests
  - pytest --cov-report term --cov-config=.coveragerc --cov=. tests
